Quire docs/newsletter archive edit jp
thegetty/quire-docs pull request #423
Opened 2021-07-21 23:28 UTC by pancaketents

Newsletter archive January to May 2021

2021-07-21 23:45 UTC, Erin-Cecele requested changes
@pancaketents This looks great. "Community Forum in Action" repeats every month from March onwards. Feels a little redundant. Let's remove that as a headline. 

I'm also not sure if there's a way to add headlines for June and July because of the Javascript. @geealbers Is there a solution for that?

2021-07-22 00:00 UTC, geealbers commented
No, you're right @Erin-Cecele, there's no way to do it since those links are being created through a script. Sorry. Might be an argument for adding the links manually each month and ditching the script? 😬

2021-07-22 00:14 UTC, Erin-Cecele commented
Ok @geealbers I can try it out and see if it's cumbersome. @pancaketents on our am call let's chat about adding June and July manually. Thanks for all your work on this today!

2021-07-26 16:01 UTC, Erin-Cecele commented on content/community/newsletter-archive.md
>  <script type="text/javascript" src="https://newsletters.getty.edu/t/t/p/hulye/0/1/0/0/0/"></script>
@pancaketents please remove this Javascript

2021-07-26 22:15 UTC, Erin-Cecele approved these changes

2021-07-26 22:15 UTC, merged