update citations and biblio section
thegetty/quire-docs pull request #599
Opened 2022-11-08 23:53 UTC by Erin-Cecele

Thank you for contributing to the Quire Documentation & Website! Please complete the form below to submit your pull request for review.

*For the Title of this pull request, please use the format "Type/Issue-#: Brief description." For Type, the options are Edit, Add, Translate. Issue-# is only needed if this pull request addresses an existing issue.*

### Checklist 

Please put an X within the brackets that apply `[X]`.

- [X] I have read the [CONTRIBUTING.md](https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md) file.

- [X] I have made my changes in a new branch and not directly in the main branch

- [X] I am requesting feedback on a draft pull request

### Is this pull request related to an open issue? If so, what is the issue number?

#549 

### Please describe the goal of this pull request and the changes that were made.

update section for 11ty changes

### Additional Comments

I added the underline HTML to give people a sense of what part will actually be linked, which I think is important. Is the display text section correct?

2022-11-09 17:44 UTC, geealbers requested changes

2022-11-09 17:44 UTC, geealbers commented on content/docs-v1/citation-bibliographies.md
> +- Add a page-level biblio using Markdown
Though I suggested this as an option in that GitHub issue, I don't think we should necessarily include it here. Better to assume users will work with refereences.yaml and not float the idea of just dumping it into markdown. Or, if you do want to keep it, I'd make it the second option, but then elaborate just a little more ....

> Skip the use of references.yaml, and instead add your bibliography directly into the page with Markdown, using list or definition list formatting

Markdown lists we have documented but we might not have definition lists included? But they work, here's a sample: 

```
apple
: a fruit you give teachers

banana
: mushy to eat, funny to slip on

orange
: a fruit and a color
```

2022-11-09 17:44 UTC, geealbers commented on content/docs-v1/citation-bibliographies.md
> +Additionally, to create a complete bibliography for your entire publication, from all the entries in the project's `references.yaml` file, you would add a `bibliography.md` file to your `content` dir
See note above about using `layout: bibliography` instead

2022-11-09 17:44 UTC, geealbers commented on content/docs-v1/citation-bibliographies.md
> +A heading can be customized to go above the page bibliography in your `content/_data/config.yaml` file. The default heading is "Bibliography".
This part is still important to keep but applies to page-level bibliographies specifically

2022-11-10 00:47 UTC, geealbers commented on content/docs-v1/citation-bibliographies.md
> +Additionally, to create a complete bibliography for your entire publication, from all the entries in the project's `references.yaml` file, you would add a `bibliography.md` file to your `content` dir
It wouldn't. `lauyout: bibliography` will create a page that has the full bibliography for the whole book (all the references in references.yaml). I don't think there's a use case for having that full biblio appear on an essay or entry page. Those will have their own page-level biblios based on usage of `% cite %`.

2022-11-10 00:53 UTC, Erin-Cecele commented on content/docs-v1/citation-bibliographies.md
> +In-text citations and bibliographies are all available in Quire. Designed to meet scholarly needs and multiple citation styles, they are easy to implement in your publications. Bibliographic referenc
Fixing this. I noticed in CC that there is also a `class: backmatter` is this required for a bibliography.md? Or is it just a Getty pubs styling preference?

2022-11-10 01:13 UTC, geealbers commented on content/docs-v1/citation-bibliographies.md
> +In-text citations and bibliographies are all available in Quire. Designed to meet scholarly needs and multiple citation styles, they are easy to implement in your publications. Bibliographic referenc
I have some open questions about Quire's use of the `backmatter` class. I don't think it's stable/tested enough to document yet. So I'd just ignore it for now

2022-11-10 18:48 UTC, Erin-Cecele commented on content/docs-v1/citation-bibliographies.md
> +```yaml
FYI I couldn't get this to display properly so I removed the tip

2022-11-10 19:04 UTC, Erin-Cecele commented
@geealbers changes have been made and are ready for review.

2022-11-10 21:43 UTC, geealbers requested changes

2022-11-10 21:43 UTC, geealbers commented on content/docs-v1/citation-bibliographies.md
> +In-text citations and bibliographies are available in Quire. They are easy to implement and designed to meet scholarly needs and multiple citation styles. Bibliographic references are stored in a YAM
This still references a bibliography shortcode

2022-11-10 21:43 UTC, geealbers commented on content/docs-v1/citation-bibliographies.md
> +These references can then be called individually from within text using the `{% cite %}` shortcode or they can appear in their entirety as a page of your publication by adding a `bibliography.md` fil
> by adding a `bibliography.md` file to your project

The file doesn't need to be named `bibliography.md` it just needs to have `layout: bibliography`

2022-11-10 21:43 UTC, geealbers commented on content/docs-v1/citation-bibliographies.md
> +You can also create a complete bibliography for your entire publication from all the entries in the project's `references.yaml` file. To do this add a `bibliography.md` file to your `content` directo
Same note about `bibliography.md` filename as above

2022-11-10 21:43 UTC, geealbers commented on content/docs-v1/citation-bibliographies.md
> +- If entries as missing from your page-level bibliography or you see output in your command-line shell referencing missing entries, then there is most likely an incorrect or absent `{% cite %}` short
> If entries as missing ...

Should presumably be "If entries are missing ..."

2022-11-10 21:43 UTC, geealbers commented on content/docs-v1/citation-bibliographies.md
> +If you want to suppress the page level bibliography but keep the in-text citations, go into the `content/_data/config.yaml` and change the value to `false`.
> page level
 
"page-level" hyphenated

2022-11-10 22:26 UTC, Erin-Cecele commented
Ok, issues resolved. Sorry about that.

2022-11-10 23:01 UTC, geealbers approved these changes

2022-11-10 23:02 UTC, merged