Edit/Issue-#575: Update Design Guide figure image and downloadable pdf
thegetty/quire-docs pull request #696
Opened 2023-09-11 21:52 UTC by jenpark-getty

Thank you for contributing to the Quire Documentation & Website! Please complete the form below to submit your pull request for review.

*For the Title of this pull request, please use the format "Type/Issue-#: Brief description." For Type, the options are Edit, Add, Translate. Issue-# is only needed if this pull request addresses an existing issue.*

### Checklist 

Please put an X within the brackets that apply `[X]`.

- [X] I have read the [CONTRIBUTING.md](https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md) file.

- [X] I have made my changes in a new branch and not directly in the main branch

- [ ] I am requesting feedback on a draft pull request

### Is this pull request related to an open issue? If so, what is the issue number?

### Please describe the goal of this pull request and the changes that were made.

Added updated Guide to the quire-docs repo, being sure to update both the figure image version and the downloadable PDF

### Additional Comments

2023-09-11 22:55 UTC, Erin-Cecele commented
looks great, @jenpark-getty!

2023-09-11 22:55 UTC, Erin-Cecele approved these changes

2023-09-12 21:41 UTC, jenpark-getty commented
I added one more commit titled update cheatsheet.md addressing the task below, please take a look!
-
[ ] Edit the Markdown page. In the YAML section there is a reference to weight: that should be order:, and to the data folder that is now _data. And then in the Shortcodes section there's a lot that needs updating. Take your best stab at it and then @Erin-Cecele or I can make any comments/edits when we review your pull request.

2023-09-12 21:44 UTC, Erin-Cecele requested changes
Great work. Can you make the fix requested below and then also remove `online: false` from the page YAML. I want to preview the page before approving. Thanks so much, @jenpark-getty.

2023-09-12 21:44 UTC, Erin-Cecele commented on content/resources/cheatsheet.md
> +A shortcode is a snippet of code inserted in a content (`.md`) file that pulls in information from other files in your project. For example, in Quire, the `% figure %` shortcode is used to insert an
Please correct shortcode references to {% figure %}, {% cite %}, etc. Thank you!

2023-09-12 21:54 UTC, jenpark-getty commented
Hey @Erin-Cecele there doesn't seem to be an online: false line in the YAML, is there another part of the file I can edit for you?

<img width="649" alt="Screenshot 2023-09-12 at 2 50 23 PM" src="https://github.com/thegetty/quire-docs/assets/144285570/83773034-6522-48f0-891e-6e2671181725">

2023-09-12 22:00 UTC, Erin-Cecele commented
@jenpark-getty Oops, apologies. I meant these two fields: 

```
menu: false
toc: false
```

2023-09-12 22:21 UTC, jenpark-getty commented
> @jenpark-getty Oops, apologies. I meant these two fields:
> 
> ```
> menu: false
> toc: false
> ```

Done!

2023-09-13 16:53 UTC, Erin-Cecele commented
Hi @jenpark-getty, everything looks good. But I'm wondering if it might be useful to point people to the parts of the documentation that elaborate on each of these items, most specifically for the shortcodes. That could be hyperlinking the shortcode to the page (`{% figure %}` would link to https://quire.getty.edu/docs-v1/figure-images/) or you could more explicitly point people to other parts of the docs ("for more information see..."). What do you think?

2023-09-13 18:33 UTC, jenpark-getty commented
That's a good idea, I'll get to it!

2023-09-21 17:16 UTC, Erin-Cecele approved these changes
Looks great. Thanks for your work on this @jenpark-getty

2023-09-21 18:16 UTC, merged