Edit/customizations variables
thegetty/quire-docs pull request #735
Opened 2024-07-23 23:30 UTC by Erin-Cecele

Thank you for contributing to the Quire Documentation & Website! Please complete the form below to submit your pull request for review.

*For the Title of this pull request, please use the format "Type/Issue-#: Brief description." For Type, the options are Edit, Add, Translate. Issue-# is only needed if this pull request addresses an existing issue.*

### Checklist 

Please put an X within the brackets that apply `[X]`.

- [X] I have read the [CONTRIBUTING.md](https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md) file.

- [X] I have made my changes in a new branch and not directly in the main branch

- [X] I am requesting feedback on a draft pull request

### Is this pull request related to an open issue? If so, what is the issue number?

#554

### Please describe the goal of this pull request and the changes that were made.

- Update Style Customization: add custom classes/ add extend 11ty templates/ update Custom CSS from v0/ add section intro and break into basic, moderate, and advanced
- Update variables.scss guide

### Additional Comments

2024-08-12 18:27 UTC, geealbers reviewed
I've made some specific comments below. As we spoke about, I didn't get into the weeds on all the details covered on the Variables page, but I think it's fine to publish as is and to post an issue/reminder for us to go back to it another time.

2024-08-13 20:47 UTC, Erin-Cecele commented
@geealbers - just pushed the requested edits!

2024-08-13 21:04 UTC, geealbers requested changes
Just one fix

2024-08-13 21:04 UTC, geealbers commented on content/docs-v1/styles-customization.md
> +$accent-color: LightGrey;
`$content-background-color: LightGrey`

2024-08-13 21:05 UTC, Erin-Cecele commented on content/docs-v1/styles-customization.md
> +$accent-color: LightGrey;
oops! Thank you!

2024-08-13 21:28 UTC, Erin-Cecele commented
@geealbers ready for your review again.

2024-08-13 21:30 UTC, geealbers approved these changes

2024-08-13 21:48 UTC, merged